import type { StorybookConfig } from '@storybook/angular';

const config: StorybookConfig = {
  stories: ['../../../libs/*/src/**/*.stories.@(ts)'],
  addons: ['@storybook/addon-a11y'],
  framework: { name: '@storybook/angular', options: {} },
  // Serve the pre-compiled Tailwind stylesheet (generated by the `storybook-css`
  // target) and link it into the preview <head>. We deliberately do NOT import it
  // through webpack — @storybook/angular swaps in Angular's CSS handling.
  staticDirs: ['../static'],
  previewHead: (head) => `${head}\n<link rel="stylesheet" href="./preview.css" />`,
};

export default config;
